version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=${WG_HOST}

      # Optional:
      - PASSWORD=${WG_PASSWORD}
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x

    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /home/pi/docker/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
