version: "3"
services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:stable"
    volumes:
      - /home/pi/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Oslo
    restart: unless-stopped
    privileged: true
    network_mode: host
