version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: "Europe/Oslo"

    volumes:
      - "/home/pi/docker/pihole/etc-pihole/:/etc/pihole/"
      - "/home/pi/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"

    # Required for the DHCP server
    cap_add:
      - NET_ADMIN
