version: "3"
services:
  mqtt-broker:
    container_name: mqtt-broker
    image: "eclipse-mosquitto:latest"
    ports:
      - "1883:1883"
    volumes:
      - /home/pi/mosquitto:/mosquitto/config
    restart: unless-stopped
