version: "3"
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    ports:
      - "8123:8123"
    volumes:
      - /home/pi/homeassistant:/config
    environment:
      - TZ=Europe/Oslo
    restart: always
    network_mode: host
