version: '3.8'
services:
  ti-cc-tool:
    image: "ckware/ti-cc-tool"
    environment:
      FIRMWARE_URL: "https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20220219.zip"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    command: [ "-ewv", "-p", "/dev/ttyUSB0", "--bootloader-sonoff-usb" ]
