version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - /home/pi/docker/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
